### ISSUE TITLE
High MOI interactive plot is not displayed

### ISSUE THREAD

**Issue by dbacsik** [jbloomlab/barcoded_flu_pdmH1N1#301]
The interactive plot for the high MOI sample appears to be missing. @andrewwbutler can you take a quick look at https://jbloomlab.github.io/barcoded_flu_pdmH1N1/ and confirm that this is not a quirk of my computer? There should be two interactive plots.

I will fix this error.

**Comment by andrewwbutler** [comment]
Yep, I can confirm that the high MOI plot is missing.

**Comment by dbacsik** [comment]
Great, thanks. I will fix the page.

________________________________

**Comment by dbacsik** [comment]
This issue was closed by PR #302
